src/Entity/Articoli.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticoliRepository")
 */
class Articoli
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateadd;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_avaiable;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $codice;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descrizione;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $dotazioni;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $danni;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $lastuser;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastmovement;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $motivation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDateadd(): ?\DateTimeInterface
    {
        return $this->dateadd;
    }

    public function setDateadd(\DateTimeInterface $dateadd): self
    {
        $this->dateadd = $dateadd;

        return $this;
    }

    public function getIsAvaiable(): ?bool
    {
        return $this->is_avaiable;
    }

    public function setIsAvaiable(bool $is_avaiable): self
    {
        $this->is_avaiable = $is_avaiable;

        return $this;
    }

    public function getCodice(): ?string
    {
        return $this->codice;
    }

    public function setCodice(string $codice): self
    {
        $this->codice = $codice;

        return $this;
    }

    public function getDescrizione(): ?string
    {
        return $this->descrizione;
    }

    public function setDescrizione(?string $descrizione): self
    {
        $this->descrizione = $descrizione;

        return $this;
    }

    public function getDotazioni(): ?string
    {
        return $this->dotazioni;
    }

    public function setDotazioni(?string $dotazioni): self
    {
        $this->dotazioni = $dotazioni;

        return $this;
    }

    public function getDanni(): ?string
    {
        return $this->danni;
    }

    public function setDanni(?string $danni): self
    {
        $this->danni = $danni;

        return $this;
    }

    public function getLastuser(): ?string
    {
        return $this->lastuser;
    }

    public function setLastuser(?string $lastuser): self
    {
        $this->lastuser = $lastuser;

        return $this;
    }

    public function getLastmovement(): ?\DateTimeInterface
    {
        return $this->lastmovement;
    }

    public function setLastmovement(?\DateTimeInterface $lastmovement): self
    {
        $this->lastmovement = $lastmovement;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getMotivation(): ?string
    {
        return $this->motivation;
    }

    public function setMotivation(?string $motivation): self
    {
        $this->motivation = $motivation;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->id;
    }
}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Articoli;
use App\Entity\Guests;
use App\Entity\Prenotazioni;
use App\Entity\Prestiti;
use App\Entity\TipoArticoli;
use App\Form\ArticoliType;
use App\Form\PrestitiType;
use DateTime;
use Symfony\Component\HttpFoundation\Response;
use Knp\Component\Pager\PaginatorInterface;
use SGK\BarcodeBundle\Generator\Generator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ResetType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ArticlesController extends AbstractController
{

    /**
     * @Route("/lista-articoli", name="lista_articoli")
     */
    public function articlesListAction(Request $request, PaginatorInterface $paginator)
    {

        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository(Articoli::class);
        $query = $repo->createQueryBuilder('a')->getQuery();

        $pagination = $paginator->paginate($query, $request->query->getInt('page', 1), 10);

        return $this->render('articles/list.html.twig', [
            'pagination' => $pagination,
            'fun' => $this
        ]);
    }

    /**
     * @Route("/nuovo-articolo", name="nuovo_articolo")
     */
    public function articlesNewAction(Request $request)
    {

        $article = new Articoli();

        $form = $this->createForm(ArticoliType::class, $article);
        $form
            ->add('submit', SubmitType::class, [
                'label' => 'Aggiungi'
            ])
            ->add('reset', ResetType::class, [
                'label' => 'Reset'
            ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article = $form->getData();
            $article->setDateAdd(new DateTime("now"));
            $article->setIsAvaiable(1);
            $article->setType($form->getData()->getType()->getId());

            $em = $this->getDoctrine()->getManager();
            $em->persist($article);
            $em->flush();

            //$this->addFlash('success', 'Articolo Aggiunto!');

            return $this->redirectToRoute('lista_articoli', [
                'toast_message' => 'Articolo aggiunto con successo'
            ]);
        }

        return $this->render('articles/add.html.twig', [
            'form' => $form->createView(),
            'page_title' => 'Aggiungi Articolo',
        ]);
    }

    /**
     * @Route("/modifica-articolo/{id}", name="modifica_articolo")
     */
    public function articlesEditAction(Request $request, $id)
    {

        $article = $this->getDoctrine()->getRepository(Articoli::class)->find($id);

        $form = $this->createForm(ArticoliType::class, $article);
        $form
            ->add('submit', SubmitType::class, [
                'label' => 'Aggiungi'
            ])
            ->add('reset', ResetType::class, [
                'label' => 'Reset'
            ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article = $form->getData();
            $article->setIsAvaiable(1);
            $article->setType($form->getData()->getType()->getId());

            $em = $this->getDoctrine()->getManager();
            $em->persist($article);

            return $this->redirectToRoute('lista_articoli');
        }

        return $this->render('articles/add.html.twig', [
            'form' => $form->createView(),
            'page_title' => 'Modifica Articolo'
        ]);
    }

    /**
     * @Route("/scheda-articolo/{id}", name="scheda_articolo")
     */
    public function articlesShowAction($id, PaginatorInterface $paginator, Request $request)
    {
        $item = $this->getDoctrine()->getRepository(Articoli::class)->find($id);

        if ($item == null) {
            $this->redirectToRoute('lista_articoli');
            $this->createNotFoundException('Articolo non trovato');
        } else {
            $em = $this->getDoctrine()->getManager();
            $dql = "SELECT a FROM App:Prestiti a WHERE a.item = $id";
            $query = $em->createQuery($dql);
            $pagination = $paginator->paginate(
                $query,
                $request->query->getInt('page', 1),
                5, [
                    'defaultSortFieldName' => 'a.date',
                    'defaultSortDirection' => 'desc'
                ]);
            $dql2 = "SELECT a FROM App:Prenotazioni a WHERE a.item = $id";
            $query2 = $em->createQuery($dql2);
            $pagination2 = $paginator->paginate(
                $query2,
                $request->query->getInt('page', 1),
                5, [
                'defaultSortFieldName' => 'a.date',
                'defaultSortDirection' => 'desc'
            ]);
        }

        $options = array(
            'code'   => $this->generateUrl('scheda_articolo', ['id' => $item->getId()]),
            'type'   => 'qrcode',
            'format' => 'png',
            'width'  => 7,
            'height' => 7,
            'color'  => array(100, 100, 100),
        );

        $generator = new Generator();
        $barcode = $generator->generate($options);

        return $this->render('articles/show.html.twig', [
            'fun' => $this,
            'pagination' => $pagination,
            'pagination2' => $pagination2,
            'item' => $item,
            'barcode' => $barcode,
            'delete' => false
        ]);

    }

    /**
     * @Route("/elimina-articolo/{id}", name="elimina_articolo")
     */
    public function articlesDeleteAction(Request $request,$id)
    {

        $item = $this->getDoctrine()->getRepository(Articoli::class)->find($id);

        $options = array(
            'code'   => $request->getUri() . $this->generateUrl('scheda_articolo', ['id' => $item->getId()]),
            'type'   => 'qrcode',
            'format' => 'png',
            'width'  => 8,
            'height' => 8,
            'color'  => array(100, 100, 100),
        );

        $generator = new Generator();
        $barcode = $generator->generate($options);

        return $this->render('articles/show.html.twig', [
            'barcode' => $barcode,
            'fun' => $this,
            'pagination' => null,
            'item' => $item,
            'delete' => true
        ]);
    }

    /**
     * @Route("/elimina-articolo/conferma/{id}", name="elimina_articolo_conferma")
     */
    public function articlesDeleteConfirmAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $item = $em->getRepository(Articoli::class)->find($id);
        $movements = $em->getRepository(Prestiti::class)->findBy(['item' => $id]);

        $em->remove($item);
        $em->flush();

        foreach ($movements as $movement) {
            $em->remove($movement);
            $em->flush();
        }



        return $this->redirectToRoute('lista_articoli');
    }


    /**
     * @Route("/aggiungi-movimento/{id}", name="aggiungi_movimento")
     */
    public function addMovementAction(Request $request, $id)
    {

        $movimento = new Prestiti();

        $form = $this->createForm(PrestitiType::class, $movimento);
        $form
            ->add('submit', SubmitType::class, [
                'label' => 'Aggiungi'
            ])
            ->add('reset', ResetType::class, [
                'label' => 'Reset'
            ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $item = $this->getDoctrine()->getRepository(Articoli::class)->find($id);

            $movimento = $form->getData();
            $movimento->setDate(new DateTime("now"));
            $movimento->setItem($id);

            $item->setIsAvaiable($form->getData()->getStatus());
            $item->setLastuser($movimento->getGuest());
            $item->setLastmovement($movimento->getDate());
            $item->setLocation($movimento->getLocation());
            $item->setMotivation($movimento->getMotivation());

            $em = $this->getDoctrine()->getManager();
            $em->persist($movimento);
            $em->flush();

            $em->flush($item);

            return $this->redirectToRoute('scheda_articolo', [
                'id' => $id
            ]);
        }

        return $this->render('movements/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("api/json/avaiabilty/{id}", name="json_avaiability")
     */
    public function aggregateJSONAvaiability($id) {

        $events = $this->getDoctrine()->getRepository(Prestiti::class)->findBy(['item' => $id]);
        $prenotazioni = $this->getDoctrine()->getRepository(Prenotazioni::class)->findBy(['item' => $id]);

        $response = new Response();
        $array = ['monthly' => []];

        foreach ($events as $event) {
            $new = [
                'id' => $event->getId(),
                'name' => $this->getDoctrine()->getRepository(Guests::class)->find($event->getGuest())->getName() . ' - PRESTITO',
                'startdate' => $event->getDate()->format("Y-m-d"),
                'enddate' => $event->getDateBack()->format("Y-m-d"),
                'starttime' => $event->getDate()->format("h:i"),
                'endtime' => $event->getDateBack()->format("h:i"),
                'color' => "#FF5733",
                'url' => ''
            ];
            array_push( $array['monthly'], $new);
        }

        foreach ($prenotazioni as $prenotazione) {
            $new = [
                'id' => $prenotazione->getId(),
                'name' => $this->getDoctrine()->getRepository(Guests::class)->find($prenotazione->getUser())->getName() . ' - PRENOTAZIONE',
                'startdate' => $prenotazione->getDate()->format("Y-m-d"),

templates/articles/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}EGInA - Database dotazioni{% endblock %}

{% block body %}
    <div class="container">
        <div class="row mt-3">
            <div class="col-12">
                <h3>{{ page_title }}</h3>
            </div>
        </div>
        <div class="row mt-3">
            {{ form_start(form) }}
            <div class="col-12">
                <div class="row">
                    <div class="col-3">
                        {{ form_label(form.codice) }}
                        {{ form_widget(form.codice) }}
                    </div>
                    <div class="col-6">
                        {{ form_label(form.name) }}
                        {{ form_widget(form.name) }}
                    </div>
                    <div class="col-3">
                        {{ form_label(form.type) }}
                        {{ form_widget(form.type) }}
                        {{ form_help(form.type) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        {{ form_label(form.dotazioni) }}
                        {{ form_widget(form.dotazioni ) }}
                    </div>
                    <div class="col-6">
                        {{ form_label(form.danni) }}
                        {{ form_widget(form.danni ) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{ form_label(form.descrizione) }}
                        {{ form_widget(form.descrizione ) }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-12 float-right">
                        {{ form_widget(form.submit) }}
                        {{ form_widget(form.reset) }}
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}

templates/articles/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}EGInA - Database dotazioni{% endblock %}

{% block body %}
    {% if toast_message is defined %}
        <div style="position: absolute; top: 0; right: 0;">
            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <strong class="mr-auto">EGInA</strong>
                    <small class="text-muted">now</small>
                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body">
                    {{ toast_message }}
                </div>
            </div>
        </div>
        <script>
            $('.toast').toast('show')
        </script>
    {% endif %}
    <div class="container">
        <div class="row mt-3">
            <div class="col-11">
                <h3>Lista Articoli</h3>
            </div>
            {% if is_granted('ROLE_ADMIN') %}
            <div class="col-1">
                <a href="{{ url('nuovo_articolo') }}" class="btn btn-success float-right btn-block"><i class="fa fa-plus"></i></a>
            </div>
            {% endif %}
        </div>
        <div class="row mt-3">
            <table class="table table-hover">
                <thead>
                <tr class="text-center">
                    <th scope="col">{% if pagination.isSorted('a.codice') %}<i class="fa fa-sort"></i> &nbsp;{% endif %}{{ knp_pagination_sortable(pagination, 'Codice', 'a.codice') }}</th>
                    <th scope="col">{% if pagination.isSorted('a.type') %}<i class="fa fa-sort"></i> &nbsp;{% endif %}{{ knp_pagination_sortable(pagination, 'Tipo', 'a.type') }}</th>
                    <th scope="col">{% if pagination.isSorted('a.name') %}<i class="fa fa-sort"></i> &nbsp;{% endif %}{{ knp_pagination_sortable(pagination, 'Nome', 'a.name') }}</th>
                    <th scope="col">{% if pagination.isSorted('a.dateadd') %}<i class="fa fa-sort"></i> &nbsp;{% endif %}{{ knp_pagination_sortable(pagination, 'Data Aggiunta', 'a.dateadd') }}</th>
                    <th scope="col">{% if pagination.isSorted('a.is_avaiable') %}<i class="fa fa-sort"></i> &nbsp;{% endif %}{{ knp_pagination_sortable(pagination, 'Stato', 'a.is_avaiable') }}</th>
                    <th scope="col">Opzioni</th>
                </tr>
                </thead>
                <tbody>
                {% for item in pagination %}
                    <tr>
                        <td>{{ item.codice }}</td>
                        <td>{{ fun.convertType(item.type) }}</td>
                        <td>{{ item.name }}</td>
                        <td>{{ item.dateAdd|date("d-m-Y") }}</td>
                        <td>
                            {% if item.isAvaiable == 1 %}
                                <span class="badge badge-pill badge-success text-success">'</span>
                            {% else %}
                                <span class="badge badge-pill badge-danger text-danger">'</span>
                            {% endif %}
                        </td>
                        <td width="150">
                                <a href="{{ url('scheda_articolo', {'id' : item.id}) }}" class="btn btn-sm btn-success"><i class="fa fa-eye"></i></a>
                            {% if is_granted('ROLE_ADMIN') %}
                                <a href="{{ url('modifica_articolo', {'id': item.id}) }}" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i></a>
                                <a href="{{ url('elimina_articolo', {'id': item.id}) }}" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="navigation">
                {{ knp_pagination_render(pagination) }}
            </div>
        </div>
    </div>

{% endblock %}

templates/articles/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}EGInA - Database dotazioni{% endblock %}

{% block body %}
    <div class="container">
        <div class="row mt-3">
            <div class="col-10">
                <h3>{{ item.name }}</h3>
            </div>
            <div class="col-2">
                <a href="{{ url('modifica_articolo', {'id': item.id }) }}" class="btn btn-secondary float-right btn-block"><i class="fa fa-edit"></i> Modifica</a>
            </div>
        </div>
        <div class="card mt-2">
            <div class="card-body">
                <div class="card-title">
                    <h5>Dati Articolo</h5>
                </div>
                <div class="row">

                    <div class="col-sm-2">
                        <img class="img-fluid" src="data:image/png;base64,{{ barcode }}" />
                    </div>
                    <div class="col-sm-6">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td>Tipo</td>
                                    <td>{{ fun.convertType(item.type) }}</td>
                                </tr>
                                <tr>
                                    <td>Codice</td>
                                    <td>{{ item.codice }}</td>
                                </tr>
                                <tr>
                                    <td>Nome</td>
                                    <td>{{ item.name }}</td>
                                </tr>
                                <tr>
                                    <td>Descrizione</td>
                                    <td>{{ item.descrizione }}</td>
                                </tr>
                                <tr>
                                    <td>Dotazione</td>
                                    <td>{{ item.dotazioni }}</td>
                                </tr>
                                <tr>
                                    <td>Parti Danneggiate</td>
                                    <td>{{ item.danni }}</td>
                                </tr>
                                <tr>
                                    <td>Stato</td>
                                    <td>{% if item.isAvaiable == 1 %}
                                            <span class="badge badge-pill badge-success text-success">'</span>&nbsp; In Magazzino
                                        {% else %}
                                            <span class="badge badge-pill badge-danger text-danger">'</span>&nbsp; Non in Magazzino
                                        {% endif %}</td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                    <div class="col-sm-4">
                        <div class="row">
                            <div id="calendar"></div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                Legenda:
                                <span class="badge" style="background-color: #FF5733">Prestito</span>
                                <span class="badge" style="background-color: #FFC300">Prenotazione</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if delete %}
            <div class="row mt-3">
                <div class="col-12">
                    <div class="alert alert-danger alert-dismissible fade show px-4 py-4" role="alert">
                        Attenzione, vuoi eliminare questo Articolo? (L'azione non è reversibile)
                        <a href="{{ url('elimina_articolo_conferma', {'id' : item.id }) }}" class="btn btn-danger btn-md float-right mt-0" style="position: relative;top: -8px;">Conferma eliminazione</a>
                    </div>
                </div>
            </div>
        {% else %}
        <div class="row mt-3">
            <div class="col-12">
                <nav class="nav nav-pills flex-column flex-sm-row">
                    <a class="flex-sm-fill text-sm-center nav-link active" href="#movimenti" data-toggle="tab" role="tab" aria-controls="movimenti" aria-selected="true">Movimenti</a>
                    <a class="flex-sm-fill text-sm-center nav-link" href="#prenotazioni" data-toggle="tab" role="tab" aria-controls="prenotazioni" aria-selected="false">Prenotazioni</a>
                </nav>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-12">
                <div class="tab-content">
                    <div class="tab-pane active" id="movimenti" role="tabpanel" aria-labelledby="home-tab">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">Data</th>
                                <th scope="col">Rientro</th>
                                <th scope="col">Utente</th>
                                <th scope="col">Luogo</th>
                                <th scope="col">Motivo</th>
                                <th scope="col">Stato</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for line in pagination %}
                                <tr>
                                    <td>{{ line.date|date("d-m-Y h:i") }}</td>
                                    <td>{{ line.dateBack|date("d-m-Y h:i") }}</td>
                                    <td><a href="{{ url('mostra_cliente', {'id': line.guest}) }}">{{ fun.convertClient(line.guest) }}</a></td>
                                    <td>{{ line.location }}</td>
                                    <td>{{ line.motivation }}</td>
                                    <td>
                                        {% if line.status == 1 %}
                                            <span class="badge badge-pill badge-success text-success">'</span>
                                        {% else %}
                                            <span class="badge badge-pill badge-danger text-danger">'</span>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="navigation">
                            {{ knp_pagination_render(pagination) }}
                        </div>
                        <div class="row mb-3">
                            <div class="col-12">
                                <a href="{{ url('aggiungi_movimento', {'id' : item.id}) }}" class="btn btn-success btn-block">
                                    <i class="fa fa-plus"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="prenotazioni" role="tabpanel" aria-labelledby="profile-tab">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">Data</th>
                                <th scope="col">Rientro</th>
                                <th scope="col">Utente</th>
                                <th scope="col">Motivo</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for line in pagination2 %}
                                <tr>
                                    <td>{{ line.date|date("d-m-Y h:i") }}</td>
                                    <td>{{ line.dateBack|date("d-m-Y h:i") }}</td>
                                    <td><a href="{{ url('mostra_cliente', {'id': line.user}) }}">{{ fun.convertClient(line.user) }}</a></td>
                                    <td>{{ line.motivation }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="navigation">
                            {{ knp_pagination_render(pagination2) }}
                        </div>
                        <div class="row mb-3">
                            <div class="col-12">
                                <a href="{{ url('nuova_prenotazione', {'id' : item.id}) }}" class="btn btn-success btn-block">
                                    <i class="fa fa-plus"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
            <script>
                $(function () {
                    $('#myTab li:last-child a').tab('show')
                })
            </script>
        {% endif %}
    </div>

{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/calendar/monthly.css') }}">
{% endblock %}
{% block javascripts %}
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="{{ asset('assets/calendar/monthly.js') }}"></script>
    <script type="text/javascript">
        $(window).load( function() {
            $('#calendar').monthly({
                mode: 'event',
                dataType: 'json',
                jsonUrl : '{{ url('json_avaiability', { 'id' : item.id }) }}',
                weekdayNameFormat: "narrow",
                stylePast: true,
            });
        });
    </script>
{% endblock %}